### ISSUE TITLE
有关数据集的问题

### ISSUE THREAD

**Issue by shijian97** [wzhlearning/fNIRSNet#1]
您好！您对于MA数据集的处理让我非常受启发，冒昧请问一下，您是否对于同一个数据集进行了脑电的数据处理，因为我使用脑电数据做分类时，准确率特别低，不知道是不是数据处理的方法有问题

**Comment by wzhlearning** [comment]
您好！感谢关注我们的工作。MA包括fNIRS和EEG两个部分，我们仅仅使用fNIRS。根据原始论文，这两种信号预处理方式是不一样的，我们提供的预处理脚本不能直接用于EEG。EEG分类Acc很低，可能原因有：1）数据预处理，建议按照原始论文；2）检查代码，例如shape、数据读取、归一化等；3）模型选择和参数，例如fNIRSNet的参数设置不一定适合EEG。希望能对您有帮助，谢谢。

**Comment by shijian97** [comment]
好的，非常感谢！
