### ISSUE TITLE
有关数据预处理的问题

### ISSUE THREAD

**Issue by shijian97** [wzhlearning/fNIRSNet#2]
您好，我从作者的原始数据中发现一个被试的文件中包含了cnt和cnt_artifact两个mat文件，其中cnt_artifact.mat是运动伪迹的数据。想请教一下您是否有对cnt.mat进行去伪迹的处理呢？
![image](https://github.com/wzhlearning/fNIRSNet/assets/31608874/beb6abba-1b3a-4211-ae49-30cab415130f)

**Comment by wzhlearning** [comment]
您好，我们没有利用cnt_artifact.mat对cnt.mat进行去伪迹。实际上，数据集原作者也没有使用cnt_artifact.mat，原文“In addition, representative motion artifacts induced by ocular and head movements were separately recorded and included in the dataset, but not intensively analyzed in this study.”。希望对你有用。

**Comment by shijian97** [comment]
非常感谢！
